FROM python:3.8-slim

ENV FLASK_ENV=development

WORKDIR /app

COPY ./logrotate/* /etc/logrotate.d/

COPY ./requirements ./requirements

RUN pip install -r requirements/dev.txt

CMD ["gunicorn", "app:app()", "-c", "gunicorn.conf.dev.py"]
