[tool.poetry]
name = "normal-oj-web"
version = "0.1.0"
description = "Backend of Normal-OJ"
authors = []
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = "^3.8"
Flask = "^2.2"
gunicorn = "^20.1"
mongoengine = "^0.24"
blinker = "^1.5"
PyJWT = "^2.5"
requests = "^2.28"
mosspy = "^1.0"
redis = "^4.4"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1"
mongomock = "^4.1"
pre-commit = "^2.20"
yapf = "^0.32"
fakeredis = "^1.9"
toml = "^0.10"
pytest-cov = "^3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
